config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  post 'books' => 'books#create'
  get 'index' => 'books#index'
  get 'books/:id' => 'books#show' ,as: 'book'
  get 'books/edit/:id' => 'books#edit' ,as: 'edit_list'
  patch 'books/:id' => 'books#update' ,as: 'update_book'
  delete 'books/:id' => 'books#destroy',as: 'destroy_book'
  get 'homes/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to book_path(@book)
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book.id)
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to'/index'
  end
    
  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local: true do |f| %>


  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Back", '/index' %>
|
<%= link_to "Show", book_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<%= form_with model: @book, local: true do |f| %>
  <p>title</p><p>body</p>
  <% @books.each do |book| %>
    <span><%= book.title %></span>
    <span><%= book.body %></span>
    <%= link_to "Show", book_path(book.id) %>
    <%= link_to "Edit", edit_list_path(book.id) %>
    <%= link_to "Destroy", destroy_book_path(book.id),method: :delete,"data-confirm" => "Are you sure?" %>
  <% end %>

  <h2>New book</h2>

    <h4>title</h4>
    <%= f.text_field:title %>

    <h4>body</h4>
    <%= f.text_area:body %>
    <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p>Book was successfully created</p>


  <p>
    <strong>Title:</strong>
    <span><%= @book.title %></span>
  </p>

  <p>
    <strong>Body:</strong>
    <span><%= @book.body %></span>
  </p>

<%= link_to "Back", '/index' %>
|
<%= link_to "Edit", edit_list_path %>

app/views/homes/top.html.erb
<h1>
    ようこそ<strong>Bookers</strong>へ
</h1>

<p>
  <syrong>Bookers</syrong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<P>印象を共有し交換できます</P>
<p>
  <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>